version: '3.8'

services:
  tutuplapak-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tutuplapak-api-dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - DATABASE_URL=postgres://tutuplapak:postgres@postgres:5432/tutuplapak_db?sslmode=disable
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_USE_SSL=false
      - MINIO_BUCKET_NAME=tutuplapak-files
      - LOG_LEVEL=debug
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - tutuplapak-network
    restart: unless-stopped
    volumes:
      # Mount source code for development (if using live reload)
      - .:/app
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:15-alpine
    container_name: tutuplapak-postgres-dev
    environment:
      - POSTGRES_DB=tutuplapak_db
      - POSTGRES_USER=tutuplapak
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - tutuplapak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tutuplapak -d tutuplapak_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: tutuplapak-minio-dev
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_dev_data:/data
    command: server /data --console-address ":9001"
    networks:
      - tutuplapak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: tutuplapak-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - tutuplapak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO Client for bucket initialization
  minio-setup:
    image: minio/mc:latest
    container_name: tutuplapak-minio-setup-dev
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/tutuplapak-files --ignore-existing;
      /usr/bin/mc policy set public myminio/tutuplapak-files;
      exit 0;
      "
    networks:
      - tutuplapak-network

  # Database Admin (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tutuplapak-pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tutuplapak.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    networks:
      - tutuplapak-network
    depends_on:
      - postgres
    restart: unless-stopped

  # Redis Commander (Redis Admin)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tutuplapak-redis-commander-dev
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - tutuplapak-network
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  minio_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local

networks:
  tutuplapak-network:
    driver: bridge
