apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutuplapak.fullname" . }}
  labels:
    {{- include "tutuplapak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.app.service.metricsPort }}
      targetPort: {{ .Values.app.service.metricsTargetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "tutuplapak.selectorLabels" . | nindent 4 }}
